// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const config =  {
    API: {
        GraphQL: {
            endpoint: 'https://2352nueinzg5zglkosnktgtmia.appsync-api.us-east-1.amazonaws.com/graphql',
            region: 'us-east-1',
            defaultAuthMode: 'apiKey',
            apiKey: 'da2-lsujzt6amfa6faaq27tohsk6ei'
        }
    }
};

export default config;