export var Classification;
(function (Classification) {
    Classification["Assassin"] = "Assassin";
    Classification["Bystander"] = "Bystander";
    Classification["Clue"] = "Clue";
})(Classification || (Classification = {}));
export var Ruleset;
(function (Ruleset) {
    Ruleset["Duos"] = "duos";
    Ruleset["Multiplayer"] = "multiplayer";
})(Ruleset || (Ruleset = {}));
export var Team;
(function (Team) {
    Team["Blue"] = "Blue";
    Team["Green1"] = "Green1";
    Team["Green2"] = "Green2";
    Team["None"] = "None";
    Team["Red"] = "Red";
})(Team || (Team = {}));
export const GetGameDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "getGame" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "getGame" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "gameId" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "PartitionKey" } }, { "kind": "Field", "name": { "kind": "Name", "value": "Ruleset" } }, { "kind": "Field", "name": { "kind": "Name", "value": "cards" }, "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "Classification" } }, { "kind": "Field", "name": { "kind": "Name", "value": "GameId" } }, { "kind": "Field", "name": { "kind": "Name", "value": "LastSelectedBy" } }, { "kind": "Field", "name": { "kind": "Name", "value": "Owner" } }, { "kind": "Field", "name": { "kind": "Name", "value": "PartitionKey" } }, { "kind": "Field", "name": { "kind": "Name", "value": "Word" } }] } }] } }] } }] };
export const GetAllGamesDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "query", "name": { "kind": "Name", "value": "getAllGames" }, "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "getAllGames" }, "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "PartitionKey" } }, { "kind": "Field", "name": { "kind": "Name", "value": "Ruleset" } }] } }] } }] };
export const CreateGameDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "mutation", "name": { "kind": "Name", "value": "createGame" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "ruleSet" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "Ruleset" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "createGame" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "ruleset" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "ruleSet" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "gameId" } }, { "kind": "Field", "name": { "kind": "Name", "value": "status" } }] } }] } }] };
export const UpdateCardDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "mutation", "name": { "kind": "Name", "value": "updateCard" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "cardInput" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "CardInput" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "updateCard" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "cardInput" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "cardInput" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "Classification" } }, { "kind": "Field", "name": { "kind": "Name", "value": "GameId" } }, { "kind": "Field", "name": { "kind": "Name", "value": "LastSelectedBy" } }, { "kind": "Field", "name": { "kind": "Name", "value": "Owner" } }, { "kind": "Field", "name": { "kind": "Name", "value": "PartitionKey" } }, { "kind": "Field", "name": { "kind": "Name", "value": "Word" } }] } }] } }] };
export const DeleteGameDocument = { "kind": "Document", "definitions": [{ "kind": "OperationDefinition", "operation": "mutation", "name": { "kind": "Name", "value": "deleteGame" }, "variableDefinitions": [{ "kind": "VariableDefinition", "variable": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } }, "type": { "kind": "NonNullType", "type": { "kind": "NamedType", "name": { "kind": "Name", "value": "ID" } } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "deleteGame" }, "arguments": [{ "kind": "Argument", "name": { "kind": "Name", "value": "gameId" }, "value": { "kind": "Variable", "name": { "kind": "Name", "value": "id" } } }], "selectionSet": { "kind": "SelectionSet", "selections": [{ "kind": "Field", "name": { "kind": "Name", "value": "status" } }, { "kind": "Field", "name": { "kind": "Name", "value": "message" } }] } }] } }] };
